config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   root 'pages#home'
   get 'gallery', to: 'pages#gallery'
   get 'about', to: 'pages#about'
   get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def gallery

  end

  def about

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def copyright_generator
  @copyright = DeboViewTool::Renderer.copyright 'Nikky Africana Salon', 'All rights reserved'
 end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #efa4ab;">
  <%= link_to "HairSalonApp", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Gallery", gallery_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HairsalonApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
  <div class="container">
    <%= yield %>
  </div>  

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

   <hr>
   <%= copyright_generator %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page<h1>

app/views/pages/contact.html.erb
<h1>This is the contact page<h1>

app/views/pages/gallery.html.erb
<h1>This is the gallery page<h1>

app/views/pages/home.html.erb
<div class=" center jumbotron">
  <h1>Hair Salon</h1>
  <%= link_to "Learn more", about_path, class: "btn btn-primary btn-lg" %>
</div>